[env]
DATABASE_URL = "postgres://postgres:password@localhost:5432/newsletter"
[tasks.test]
command = "cargo"
args = ["test", "--all-features"]

[tasks.cover]
install_crate = "cargo-tarpaulin"
command = "cargo"
args = ["tarpaulin", "--ignore-tests"]
dependencies = ["test"]

[tasks.lint]
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]
dependencies = ["cover"]

[tasks.format]
command = "cargo"
args = ["fmt", "--all", "--", "--check"]
dependencies = ["lint"]

[tasks.auditing]
install_crate = "cargo-audit"
command = "cargo"
args = ["audit", "--ignore", "RUSTSEC-2023-0071"]
dependencies = ["format"]

[tasks.ga]
dependencies = ["auditing"]
command = "git"
args = ["add", "."]

[tasks.gc]
dependencies = ["ga"]
command = "git"
args = ["commit", "-m", "${@}"]

[tasks.push]
dependencies = ["gc"]
command = "git"
args = ["push"]

[tasks.unused]
install_crate = "cargo-udeps"
command = "cargo"
args = ["+nightly", "udeps"]

[tasks.btest]
env = {"TEST_LOG" = true}
install_crate = "bunyan"
script = """
cargo test | bunyan
"""

