[core]
markdown.file_extensions = ["md", "markdown"]
text_sync = "full"
title_from_heading = true
[code_action]
toc.enable = true
create_missing_file.enable = true
[completion]
candidates = 50
wiki.style = "title-slug"
