application:
  port: 3000
database:
  require_ssl: false
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email:
  base_url: "https://api.unisender.com"
  sender: "test@gmail.com"
  apikey: "api-key"
  timeout: 10000
